[2024-02-05T07:36:21.898+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: user_processing.inserting_data manual__2024-02-05T07:36:18.886131+00:00 [queued]>
[2024-02-05T07:36:21.929+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: user_processing.inserting_data manual__2024-02-05T07:36:18.886131+00:00 [queued]>
[2024-02-05T07:36:21.930+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T07:36:21.930+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-05T07:36:21.931+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T07:36:21.958+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): inserting_data> on 2024-02-05 07:36:18.886131+00:00
[2024-02-05T07:36:21.967+0000] {standard_task_runner.py:52} INFO - Started process 70258 to run task
[2024-02-05T07:36:21.971+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'inserting_data', 'manual__2024-02-05T07:36:18.886131+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmpx110ul0o', '--error-file', '/tmp/tmpzbjne6q9']
[2024-02-05T07:36:21.973+0000] {standard_task_runner.py:80} INFO - Job 21: Subtask inserting_data
[2024-02-05T07:36:22.070+0000] {task_command.py:371} INFO - Running <TaskInstance: user_processing.inserting_data manual__2024-02-05T07:36:18.886131+00:00 [running]> on host fe2863c78e2f
[2024-02-05T07:36:22.184+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=inserting_data
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T07:36:18.886131+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-05T07:36:18.886131+00:00
[2024-02-05T07:36:22.204+0000] {base.py:68} INFO - Using connection ID '***_postgres' for task execution.
[2024-02-05T07:36:22.212+0000] {sql.py:315} INFO - Running statement: INSERT INTO users (firstname, lastname, country, username, password, email)
            VALUES 
                ('John', 'Doe', 'USA', 'johndoe', 'password123', 'john.doe@example.com'),
                ('Jane', 'Smith', 'Canada', 'janesmith', 'password456', 'jane.smith@example.com'), parameters: None
[2024-02-05T07:36:22.214+0000] {sql.py:324} INFO - Rows affected: 2
[2024-02-05T07:36:22.237+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=inserting_data, execution_date=20240205T073618, start_date=20240205T073621, end_date=20240205T073622
[2024-02-05T07:36:22.266+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-05T07:36:22.317+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
